language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

script:
  - composer install
  - phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
